### ISSUE TITLE
Alternative to PropertySet

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#71] opened 2015-09-23 02:24 UTC
At today's developer meeting, @pixelzoom said the primary features he wants from PropertySet are: (a) ease of creating a group of Properties and (b) resetting them as a group.

Whenever we dynamically create instance attributes, such as `visibleProperty`, my IDE has a horrible time trying to track them down for navigation and highlighting.

If we switch to a paradigm where PropertySet is predominantly for creating and resetting properties and we use the Property API for all other features, then we could choose this alternative (it is left as an exercise for the reader to infer the implementation of addResettable):

```js
    this.visibleProperty = addResettable( new Property( true ) );
    this.colorProperty   = addResettable( new Property( 'green' ) );
    this.nameProperty    = addResettable( new Property( 'Alice' ) );
```

In my opinion, this is not too much more verbose than

```js
    PropertySet.call( this, {
      visible: true
      color: 'green',
      name: 'Alice'
    } );
```

Voila, now my IDE can highlight and navigate the properties.  We should discuss this approach.

**Comment by samreid** [comment] 2015-09-23 02:26
We could do the same for EmitterSet (proposed in #70).  Though in that case, since there is no "fire all emitters at once" functionality, EmitterSet may be completely unnecessary and we could just stick with one Emitter per event type in that case.

**Comment by samreid** [comment] 2015-09-30 17:10
I guess I'd like to investigate this when I'm starting on a new sim.  Unassigning for now.

**Comment by samreid** [comment] 2015-10-16 04:47
> I guess I'd like to investigate this when I'm starting on a new sim. Unassigning for now.

I'll be starting Circuit Construction Kit soon and am thinking of taking this strategy for a test drive.  Thoughts from @jbphet @jonathanolson @aaronsamuel137 before I start?  I'll flag for dev-meeting in case we don't get a chance to discuss it before then.

**Comment by jonathanolson** [comment] 2015-10-20 16:15
I've personally found it helpful to support ```this.visible``` as an access pattern, so that if 'visible' doesn't have to be a Property anymore, it's easy to convert back to a normal object property (and vice versa).

The proposed way of supporting this:
```js
this.visibleProperty = object.addResettable( 'visible', new Property( true ) );
```
sounds way more verbose and harder to read than:
```js
{ visible: true }
```

**Comment by pixelzoom** [comment] 2015-10-21 14:23
I prefer the PropertySet pattern.

**Comment by samreid** [comment] 2015-10-23 05:51
Here is a crazy hack that lets us gain navigation and highlighting (without developing our own plugin) and still using PropertySet object literal constructor.  After declaring the PropertySet, assign the Properties to themselves.  We could strip this out for production, or enable it only in assert:

```js
    PropertySet.call( this, {

      // Property that indicates where in model space the upper left corner of this shape is.  In general, this should
      // not be set directly outside of this type, and should only be manipulated through the methods defined below.
      position: initialPosition,

      // Flag that tracks whether the user is dragging this shape around.  Should be set externally, generally by the a
      // view node.
      userControlled: false,

      // Flag that indicates whether this element is animating from one location to another, should not be set externally.
      animating: false,

      // Value that indicates how faded out this shape is.  This is used as part of a feature where shapes can fade
      // out.  Once fade has started, it doesn't stop until it is fully faded, i.e. the value is 1.  This should not be
      // set externally.
      fadeProportion: 0,

      // A flag that indicates whether this individual shape should become invisible when it is done animating.  This
      // is generally used in cases where it becomes part of a larger composite shape that is depicted instead.
      invisibleWhenStill: true
    } );
    //noinspection SillyAssignmentJS Identify properties for navigation and highlighting
    this.invisibleWhenStillProperty = this.invisibleWhenStillProperty;

    // This one is not identified above, and is marked as an error and un-navigable
    this.userControlledProperty.link(function(){});
    
    // This one is identified above, and hence marked as a valid attribute and navigable.
    this.invisibleWhenStillProperty.link(function(h){});
```

**Comment by samreid** [comment] 2015-10-23 05:52
Screenshot of the latter two statements:

![image](https://cloud.githubusercontent.com/assets/679486/10685492/e8f8c4f0-7917-11e5-822e-feebffe6acef.png)

**Comment by samreid** [comment] 2016-09-23 03:31
Here's a proposal for a pattern that would replace usage of PropertySet:

```js
// Copyright 2016, University of Colorado Boulder

/**
 * Person class
 * @author Sam Reid (PhET Interactive Simulations)
 */
define( function( require ) {
  'use strict';

  // modules
  var inherit = require( 'PHET_CORE/inherit' );
  var Property = require( 'AXON/Property' );

  function Person( tandem ) {
    this.heightProperty = new Property( 123, {
      tandem: tandem.createTandem( 'heightProperty' )
    } );
    this.ageProperty = new Property( 99, {
      tandem: tandem.createTandem( 'ageProperty' ),
      allowedValues: [ 1, 2, 3 ]
    } );

    this.resetPerson = function() {
      this.heightProperty.reset();
      this.ageProperty.reset();
    };
  }

  return inherit( Object, Person, {
    reset: function() {
      this.resetPerson();
    }
  } );
} );
```

It parallels our current strategy for dispose. (Note that our dispose strategy is under discussion for a different pattern).

**Comment by pixelzoom** [comment] 2016-09-23 18:42
@samreid said:
> Note that our dispose strategy is under discussion for a different pattern).

I've been unsuccessful in locating the issue where we were discussing this.

**Comment by pixelzoom** [comment] 2016-09-23 18:43
@samreid said:
> Note that our dispose strategy is under discussion for a different pattern).

I've been unsuccessful in locating the issue where we were discussing this.  Would be good to review, since I recall that we decided on an approach similar to what @samreid has proposed, then put the brakes on due to some concerns.

**Comment by samreid** [comment] 2016-09-23 18:48
I found the issue over here: https://github.com/phetsims/axon/issues/84

**Comment by pixelzoom** [comment] 2016-09-23 18:48
In https://github.com/phetsims/axon/issues/71#issuecomment-249094002, @samreid proposed a pattern that would replace PropertySet.   Looks like the proposal is to dump `PropertySet` (which imo creates more problems than it solves), have the client instantiate all `Property` instances directly, and have the client write their own `reset` function.  I like it. This is what I was doing in my earlier sims, and oh how I wish I'd stuck with that approach.

**Comment by pixelzoom** [comment] 2016-09-23 18:51
#84 is where discussion about an alternative started. But it's not the issue where we discussed various patterns and decided on our current pattern.

**Comment by samreid** [comment] 2016-09-23 19:56
Perhaps it was https://github.com/phetsims/axon/issues/93 ?

**Comment by pixelzoom** [comment] 2016-09-23 20:02
Yep thanks, #93 it was.  And the related example is phet-info `DisposeExampleNode`, which has been changed so many time that it no longer resembles the original pattern.

**Comment by samreid** [comment] 2016-09-23 20:24
Do you like this pattern?

```js
    // @public Properties owned by this instance
    this.myPublicProperty = new Property( 0, { disposable: this } );
    this.myEmitter = new Emitter( { disposable: this } );
    this.myEvents = new Events( { disposable: this } );
```

If so, we could expand it to cover resettable too.

```js
    this.myPublicProperty = new Property( 0, { disposable: this, resettable: this } );
    this.myEmitter = new Emitter( { disposable: this} );
    this.myEvents = new Events( { disposable: this } );
```

In my opinion, dispose and reset are very similar and we should solve them similarly.

**Comment by samreid** [comment] 2016-09-23 20:31
Upon reflection, the pattern above seems somewhat "magical", and perhaps we should stick with the traditional pattern:

```js
this.disposeMyClass = function(){
 thing1.dispose();
 thing2.dispose();
}

this.resetMyClass = function(){
 something1.reset();
 something2.reset();
}
```

It is unfortunate that the creation/disposal/reset get spread out, but perhaps it is better than the alternative.

**Comment by pixelzoom** [comment] 2016-09-23 20:32
@samreid asked in https://github.com/phetsims/axon/issues/71#issuecomment-249293425
> Do you like this pattern?

-1

**Comment by samreid** [comment] 2016-09-23 20:36
Do you like this pattern? https://github.com/phetsims/axon/issues/71#issuecomment-249294946

**Comment by pixelzoom** [comment] 2016-09-23 20:42
@samreid asked:
> Do you like this pattern? https://github.com/phetsims/axon/issues/71#issuecomment-249294946

+1. Keeps it simple and obvious.

**Comment by samreid** [comment] 2016-09-24 02:47
Putting this issue on hold until we discuss #102

**Comment by jonathanolson** [comment] 2016-09-24 05:43
The above code example was:
```js
  function Person( tandem ) {
    this.heightProperty = new Property( 123, {
      tandem: tandem.createTandem( 'heightProperty' )
    } );
    this.ageProperty = new Property( 99, {
      tandem: tandem.createTandem( 'ageProperty' ),
      allowedValues: [ 1, 2, 3 ]
    } );

    this.resetPerson = function() {
      this.heightProperty.reset();
      this.ageProperty.reset();
    };
  }

  return inherit( Object, Person, {
    reset: function() {
      this.resetPerson();
    }
  } );
```
yet I'm wondering why there is a separate disposal function (particularly one that is a different function for every instance). Why not:
```js
  function Person( tandem ) {
    this.heightProperty = new Property( 123, {
      tandem: tandem.createTandem( 'heightProperty' )
    } );
    this.ageProperty = new Property( 99, {
      tandem: tandem.createTandem( 'ageProperty' ),
      allowedValues: [ 1, 2, 3 ]
    } );
  }

  return inherit( Object, Person, {
    reset: function() {
      this.heightProperty.reset();
      this.ageProperty.reset();
    }
  } );
```

Also additionally, why don't we use Property.addProperty or something that lets us access ```person.age``` instead of ```person.ageProperty.value```?

**Comment by samreid** [comment] 2016-09-24 16:49
> yet I'm wondering why there is a separate disposal function

You are right, if all of the things to be reset are member variables, then there is no need for a closure function.  If there are closure variables in the constructor, then we can use the `this.resetPerson` pattern.

> Also additionally, why don't we use Property.addProperty or something that lets us access ```person.age``` instead of ```person.ageProperty.value```?

For simulation code, @pixelzoom and I have discussed getting rid of the "automatically generate es5 getter/setter" pattern, because it makes it impossible to know if there will be side effects when a value is set and obfuscates whether you are working with an axon Property or an object property.  There may be places where we still want to formalize a pattern for this (say, if scenery.Node used `visibleProperty` instead of managing its own `_visible`.), but this would be the exception rather than the rule.

**Comment by pixelzoom** [comment] 2016-09-26 21:12
I'm test driving the approach of using Property instead of PropertySet in models-of-the-hydrogen-atom, where I had 5 PropertySets. See https://github.com/phetsims/models-of-the-hydrogen-atom/commit/534a9c0aa0931bfd53f93b5592e6c50c7a019560 to compare the approaches. Having to implement reset is (as expected) a bit of a pain. But being able to navigate to Properties is wonderful, and this approach looks like it will be much easier to instrument for PhET-iO.

**Comment by pixelzoom** [comment] 2016-09-26 21:30
Here are the number of PropertySet usages in my sims:

> function-builder: 1
graphing-lines: 5
hookes-law: 5
litmus: 1
molarity: 1
molecule-polarity: 4
ph-scale: 3
reactants-products-and-leftovers: 5

I've avoided PropertySet's ES5 set/get features. Based on my experience converting models-of-the-hydrogen-atom, I should be able to convert these at the rate of about 5/min per Property, or 125 minutes total (just over 2 hours).

Here are the number of PropertySet usages in sims that I've adopted:

> acid-base-solutions: 3
balancing-chemical-equations: 7
color-vision: 4
example-sim: 1
plinko-probability: 2

These sims may be using PropertySet's ES5 set/get features, so I'll estimate about 10/min per Property to convert, or 170 minutes total (just under 3 hours).  I suspect that will go faster, but I'm being conservative.

**Comment by pixelzoom** [comment] 2016-09-26 22:42
Experimented with converting a couple of sims (molarity, function-builder).  The estimates for my sims are perhaps a tad optimistic, due to usages of `addProperty`, `addDerivedProperty` and `multilink`.  But still not very difficult to convert.

**Comment by pixelzoom** [comment] 2016-09-27 03:04
RPAL was apparently a sim where I experimented with using the ES5 setters/getters for Properties. Converting it (see commit above) was not fun, was error prone, and required a lot of regression testing.

**Comment by samreid** [comment] 2016-09-27 05:11
This will be a problem in porting.  Will swapping out the bodies of the ES5 getter setters for informative assert statements help with this step?  I'm thinking of something like changing:

```js
    /**
     * Adds a getter and setter using ES5 get/set syntax, similar to https://gist.github.com/dandean/1292057, same as in github/Atlas
     * @param {string} propertyName
     * @public
     */
    addGetterAndSetter: function( propertyName ) {
      var property = this[ propertyName + SUFFIX ];

      Object.defineProperty( this, propertyName, {

        // Getter proxies to Model#get()...
        get: function() {
          return property.get();
        },

        // Setter proxies to Model#set(attributes)
        set: function( value ) { property.set( value ); },

        // Make it configurable and enumerable so it's easy to override...
        configurable: true,
        enumerable: true
      } );
    },
```

to

```js
    /**
     * Adds a getter and setter using ES5 get/set syntax, similar to https://gist.github.com/dandean/1292057, same as in github/Atlas
     * @param {string} propertyName
     * @public
     */
    addGetterAndSetter: function( propertyName ) {
      var property = this[ propertyName + SUFFIX ];

      Object.defineProperty( this, propertyName, {

        // Getter proxies to Model#get()...
        get: function() {
          assert && assert( false, 'found usage of es5 getter for ' + propertyName );
          return property.get();
        },

        // Setter proxies to Model#set(attributes)
        set: function( value ) {
          assert && assert( false, 'found usage of es5 setter for ' + propertyName );
          property.set( value );
        },

        // Make it configurable and enumerable so it's easy to override...
        configurable: true,
        enumerable: true
      } );
    },
```

or we could aggregate stack traces like done in phetAllocation.js and make a large report about places that need to be ported for each sim.

**Comment by jonathanolson** [comment] 2016-09-27 22:22
I noted in October in this issue:

> I've personally found it helpful to support this.visible as an access pattern, so that if 'visible' doesn't have to be a Property anymore, it's easy to convert back to a normal object property (and vice versa).

I'm fine with removing PropertySet usage from my sims, but I find ES5 getters to be beneficial (I'd like to use Property.addProperty), and prefer assigning persistent variables to fields to have dispose() functions on the prototype, rather than duplicated closures for every object instance.

Do others mind if I replace the PropertySet pattern with the (slightly modified) pattern I've described?

**Comment by samreid** [comment] 2016-09-28 03:03
I agree Node.js (for instance) needs a `visible` ES5 getter/setter.  Are you arguing that simulations should have ES5 get/set for all Properties as well?  Automatically generated functions have been clumsy for my IDE navigating and highlighting, and @pixelzoom has said development/maintenance has been better when using direct property references instead of automatically generated ES5 getters and setters.

Things may be simpler/better if we have a standard way of creating Property instances (using the `new` operator).  If we decide to support ES5 get/set adapters for properties, we may wish to do that with an auxiliary function like so:

```js
    this.heightProperty = new Property( 123, {
      tandem: tandem.createTandem( 'height' ),
      phetioValueType: TNumber( 'meters' ),
      validate: function( value ) {
        return value >= 100;
      }
    } );
    Object.defineProperty( this, 'height', this.heightProperty.getDescriptor() );
```

> I've personally found it helpful to support this.visible as an access pattern, so that if 'visible' doesn't have to be a Property anymore, it's easy to convert back to a normal object property (and vice versa).

In my experience, it has been rare to need to convert an object from normal object property <=> axon Property, at least during simulation development.

**Comment by jonathanolson** [comment] 2016-09-28 04:34
> Are you arguing that simulations should have ES5 get/set for all Properties as well?

Didn't mean all, but it seems like a potentially appropriate default.

> If we decide to support ES5 get/set adapters for properties, we may wish to do that with an auxiliary function like so:

Setting ```this.heightProperty``` and having another statement to add ES5 getter/setter seems quite clumsy. I was thinking as a single statement (```Property.addProperty( this, 'height', ... )```) that takes care of all of the settings.

Having addProperties (similar to PropertySet's constructor) would help for defining a big block of properties:
```js
Property.addProperties( this, {
  height: { value: 10, ... },
  velocity: { value: 20, ... },
  ...
} );
```

> One more thought about object properties vs Axon Properties. If something is an axon Property, then code should typically access its value through link or multilink, right?

Many of the properties I was using (granted a while ago) had maybe 1 place where they were listened to, but were accessed all over. I'd prefer to avoid ```this.velocityProperty.get()``` compared to ```this.velocity```.

> In my experience, it has been rare to need to convert an object from normal object property <=> axon Property, at least during simulation development.

I guess I was just stating one advantage (although I remember starting things as properties, later checking everything to see if it was actually listened to, and if not demoting it).

Personally, things seem easier when interfaces are more consistent. Instead of saying "I need to look up whether this particle has velocity or velocityProperty" when you need to get or set the value, it's a lot easier to say "If it has velocity, it's particle.velocity for getting/setting. If I need to listen to it, it's particle.velocityProperty".

**Comment by pixelzoom** [comment] 2016-09-28 16:11
@samreid said:
> In my experience, it has been rare to need to convert an object from normal object property <=> axon Property, at least during simulation development.

And when it is necessary, I think that it's actually beneficial to have to change the var name.  The ES5 set/get not only obfuscates what's really going on, but makes it difficult to locate Property usage.

**Comment by samreid** [comment] 2016-09-28 20:21
@andrewadare also mentioned a preference to move away from automatically generated property variables, we should discuss this in person on Thursday.

**Comment by jonathanolson** [comment] 2016-09-28 23:38
I'll make a brief case for why I like the ES5 getters/setters in general:

### Interfaces for getting and setting things

To me, it's about interfaces. Using height as an example, you either want to retrieve the current height of an object, or set the current height of an object. It leaks information and makes things hard to change when internal implementation details of the object are exposed in the interface.

When an object has an API to retrieve or set the height that is ```object.height``` or ```object.height = value```, it is the most flexible and encapsulated (since they could be ES5 getters/setters). The client generally does not need to know how they are implemented as long as they work (returns a height, and sets the height). The main exception is if there are side-effects that interact with what the client is doing. The object may not even have height stored internally as a property (forwarding things to another object).

When an object has an API to retrieve or set the height that is ```object.heightProperty.get()``` or ```object.heightProperty.set( value )```, it is less flexible and more verbose. It also exposes implementation details that you only care about if you need to listen to the height. In the object, you now can't easily replace this with a simple property, ES5 getters, or any equivalent of object.getHeight() / object.setHeight( value ) if you need more custom logic.

Thus if we assume that any usage of ```object.height = value``` is setting a property on the object directly, then to be future-proof to modifications, we'd never want to expose that in an object's API.

If everything being a Property wouldn't have a performance overhead AND wouldn't be as verbose as it is, I'd advocate always using them for things that you'd want to get/set/listen to. Instead, JS has the built-in flexibility with ES5 getters/setters.

### Obfuscation

The ES5 getter/setter obfuscation, searchability, refactoring, and IDE highlighting issues are just as present for Scenery, and it probably has the most usage of ES5 across all sims, so I'd like to discuss using that as an example (as if ES5 getter/setter problems should be changed, it would be the main place).

Besides performance optimization, generally people don't need to know what setting node.height is, or what getting path.bounds does. Node has interfaces that behave as the ES5 setters/getters, and I think it is valuable. Many behave like Properties, some with extra behavior (things can be listened to), and almost every setter has Scenery-internal side effects that notify what needs to be repainted/updated.

I think it's a benefit (not a problem) that it obfuscates what is going on behind the scenes. Not every developer has to know all of the internal workings of Scenery. You shouldn't have to remember that setting node.cursor is basically just internally setting a property on Node while setting node.centerX triggers many things and doesn't even store the value. The interface is ```node.cursor``` and ```node.centerX```, not ```node.centerXDerivedProperty.get()```.

If ES5 setters/getters are a problem with obfuscation, should we have a developer refactor a sim to not use them? E.g.:
```js
thumbNode.left = handNode.centerX - ( 0.25 * thumbNode.width );
```
turns to
```js
thumbNode.setLeft( handNode.getCenterX() - ( 0.25 * thumbNode.getWidth() ) );
```
or if we turn them to use the xProperty interface only (like is suggested for sims?):
```js
thumbNode.leftProperty.set( handNode.centerXProperty.get() - ( 0.25 * thumbNode.widthProperty.get() ) );
```

**Comment by pixelzoom** [comment] 2016-09-29 16:54
@jonathanolson said:
> I think it's a benefit (not a problem) that it obfuscates what is going on behind the scenes.

I think you're confusing obfuscation with encapsulation. Obfuscate means to render obscure, unclear, or unintelligible; bewilder. I don't think that's the intention in scenery.

Scenery fully encapsulates Properties (e.g. node.center, node.cursor) -- there's no need for the client to know that these things are Properties.  Usage of PropertySet does *not* encapsulate Properties -- the client needs to access Properties for linking, unlinking, passing individual Properties, etc. This lack of encapsulation the fundamental problem that results in multiple methods (and names!) for accessing a Property. And having multiple methods (and especially names) results in obfuscation.

**Comment by jonathanolson** [comment] 2016-09-29 17:46
> I think you're confusing obfuscation with encapsulation. Obfuscate means to render obscure, unclear, or unintelligible; bewilder. I don't think that's the intention in scenery.

I'm aware, it just seemed from previous comments that the word "obfuscate" was being used to describe how ES5 getters/setters made the encapsulated behavior unclear (because it was hidden whether Property was used or not).

> Usage of PropertySet does not encapsulate Properties -- in adding to setting/getting their values, the client needs to access Properties for linking, unlinking, passing individual Properties, etc.

But in my experience, most usage was access, followed by retrieval, and many (most?) clients did not need to use the other features Property provides. If something starts off get/set only as a property (not Property), then needs to be listened to, that would mean every get/set needs to be updated to a blahProperty.get/set, possibly across many simulations.

If the experience other developers have had is substantially different, please let me know.

> This lack of encapsulation results in multiple methods (and names!) for accessing a Property. And having multiple methods (and especially names) results in obfuscation.

Understood, but it also allows concise and hopefully easier to read code. Scenery allows ```new Node( { visible: false } )``` and ```node.visible = false```. Should we disallow the constructor options, or disallow the ES5 getter and force users to use mutate? I'd prefer to keep both in the Scenery case and have the option for both in sim code.

**Comment by pixelzoom** [comment] 2016-09-29 18:02
> But in my experience, most usage was access, followed by retrieval, and many (most?) clients did not need to use the other features Property provides.

In my experience this is not the case is sim code, where PropertySet is most commonly used for model elements and collection of view-specific Properties.  Sims need to link/unlink from Properties, and pass Properties to other functions, where they are no longer part of a PropertySet and the Property API must be used directly.

**Comment by pixelzoom** [comment] 2016-09-29 18:07
@jonathanolson I'm also wondering why you keep using scenery as an example. It does not use PropertySet.

**Comment by jonathanolson** [comment] 2016-09-29 18:33
> @jonathanolson I'm also wondering why you keep using scenery as an example. It does not use PropertySet.

It uses ES5 getters/setters in much the same way, and the main argument against Property.addProperty (not PropertySet) seems to be the ES5 getters/setters. If there are arguments to not use ES5 setters/getters in general, they would apply to Scenery.

**Comment by samreid** [comment] 2016-09-29 18:42
I agree with @jonathanolson points, but some of my main complaints about PropertySet are about practical use in my IDE.  If I declare a hello property, my IDE flags these usages as an error because they are dynamically created:

![image](https://cloud.githubusercontent.com/assets/679486/18967378/30d19fe4-8642-11e6-82f0-aec6aa18a7bd.png)

If I use `this.helloProperty = new Property(...)`, this problem goes away.

**Comment by samreid** [comment] 2016-09-29 18:50
@pixelzoom says one problem is there are too many ways to do the same thing.  We could address this by making the Property instance private, and exposing link functions such as `linkHello` or something.

**Comment by jessegreenberg** [comment] 2016-09-29 19:03
@ariel-phet recommends that all developers try to remove PropertySet from a place in a sim.  This would give us more context to really feel what it would be like to try the alternative.  Leaving developer-meeting label so that we can all discuss next week.

**Comment by samreid** [comment] 2016-09-29 19:06
Another place where PropertySet has been awkward, subclassing and adding properties in the subclass.  For instance:

```js
function CircuitConstructionKitModel( tandem, additionalProperties, additionalTandemSetEntries, additionalTypeEntries, options ) {
  var self = this;
  options = _.extend( { circuit: null }, options );
  PropertySet.call( this, _.extend( {
    running: true // {boolean} @public changes whether the light bulb brightness and ammeter/voltmeter readouts can be seen
  }, additionalProperties ), {
    tandemSet: _.extend( {
      running: tandem.createTandem( 'runningProperty' )
    }, additionalTandemSetEntries ),
    phetioValueTypeSet: _.extend( {
      running: TBoolean
    }, additionalTypeEntries )
  } );
```

**Comment by samreid** [comment] 2016-09-29 19:15
This syntax highlights properly:

![image](https://cloud.githubusercontent.com/assets/679486/18968541/a7ad21ac-8646-11e6-9182-67a95e54a7f2.png)

And highlights and navigates properly from external usage:

![image](https://cloud.githubusercontent.com/assets/679486/18968558/b8bc602a-8646-11e6-859c-37b84ef40677.png)

**Comment by samreid** [comment] 2016-10-06 16:15
I experimented with using Property and Object.defineProperty in BlackBoxScreenModel.

**Comment by jessegreenberg** [comment] 2016-10-06 18:04
I am experimenting with replacing PropertySet in molecules-and-light.  Since PropertySet extends Events, this also helps deprecate Events since ```trigger``` and ```on``` are no longer available for model types that extended PropertySet.

**Comment by samreid** [comment] 2016-10-06 18:24
Consensus: We'll proceed with using vanilla properties without ES5 get/set, with the option to revisit Object.defineProperty in the future.

**Comment by pixelzoom** [comment] 2016-10-06 19:17
All sims that I'm responsible for no longer use PropertySet. See https://github.com/phetsims/axon/issues/71#issuecomment-249703484.

**Comment by jonathanolson** [comment] 2016-10-13 15:48
Anything relevant for developer meeting today?

**Comment by samreid** [comment] 2016-10-13 17:51
@andrewadare and I identified a way to catch calls to es5 get/set: in PropertySet.js, modify the get/set implementations to output an error for when your property is accessed.

**Comment by jbphet** [comment] 2016-10-17 16:12
I have updated Expression Exchange to no longer use PropertySet, and @aadish has been assigned to do the same for Build an Atom.  I miss the conciseness of the PropertySet way of doing things, but IMO it is clearly more explicit to have models that don't use it.

**Comment by jbphet** [comment] 2016-10-20 18:17
@aadish has completed this for Build and Atom and Isotopes and Atomic Mass.

**Comment by jbphet** [comment] 2016-10-20 18:18
Discussed in 10/20/2016 developer meeting and we agreed to move forward with this.  Closing the issue. @andrewadare will add this to the code style guidelines.

**Closed** 2016-10-20 18:19 UTC
Labels: meeting:developer, status:on-hold

**Comment by andrewadare** [comment] 2016-10-20 18:38
Done, added this:

The use of Property is preferred to PropertySet in new sim code. This is primarily for clarity: PropertySet supports ES5 setters and getters, so that e.g. this.positionProperty could be accessed as this.position or modified as this.position = new Vector2( 1.23, 4.56 ). This leads to ambiguity for the reader as to whether this.position is an ordinary var, or whether it’s shorthand for a PropertySet instance. When Property is used, assignment must done like this: 

this.positionProperty.set( new Vector2( 1.23, 4.56 ) ) or
this.positionProperty.value = new Vector2( 1.23, 4.56 ) 

Although more verbose, this syntax is unambiguous. Similarly, use either

this.positionProperty.get()
this.positionProperty.value

for access.

**Comment by jonathanolson** [comment] 2016-10-25 21:59
Just noting this for the future (I'm fine with decision made above):

Converted make-a-ten to use Property instead of PropertySet. It has 28 usages of *Property.link* and 1 usage of *Property.unlink* (probably indicates memory leaks), compared to 103 usages of *Property.value, continuing my observation above:

> But in my experience, most usage was access, followed by retrieval, and many (most?) clients did not need to use the other features Property provides.
