### ISSUE TITLE
remove Emitter emit1, emit2, emit3

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#218] opened 2019-02-09 20:52 UTC
In light of work like https://github.com/phetsims/scenery/issues/928 and https://github.com/phetsims/axon/issues/211 ...

Emitter `emit1`, `emit2`, and `emit3` should be deleted. They are all deprecated. @samreid recently changed their implementations to be nearly identical and call `emit`, see https://github.com/phetsims/axon/commit/880b3119f7bbd4ea81417db15a50ab22252d4d44.   And they would be relatively easy to replace with `emit` using global string replacement. 

Occurrences:
70 emit1
9 emit2
6 emit3

Assigning to @ariel-phet to prioritize and assign.

**Comment by samreid** [comment] 2019-02-10 04:17
The reason I didn't just tackle this as part of https://github.com/phetsims/axon/issues/211 was that `emit` requires `validators` whereas `emit1,2,3` ignore validation.  So we have these kind of options:

a) add a (temporary?) feature to Emitter that ignores validation
b) use `validators` like `[Any]` for `emit1`, `[Any,Any]` for `emit2` etc.
c) add the correct validators for each Emitter as part of this port.

(c) is the preferable long term solution, but it would be nice to shape up the Emitter validator API first, as decided in https://github.com/phetsims/axon/issues/204#issuecomment-461681543

**Comment by zepumph** [comment] 2019-02-27 21:45
duplicate of #211

**Closed by zepumph** 2019-02-27 21:45 UTC
