### ISSUE TITLE
TODO: assert that phetioID is defined

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#245] opened 2019-04-28 18:42 UTC
@zepumph looks like you added this TODO in https://github.com/phetsims/axon/commit/923055d9c5741cc7888f91a311a835c28b0e5492 while working on https://github.com/phetsims/energy-skate-park-basics/issues/452.  Please address it, or create an associated issue.

ObservableArrayIO:

```js
              return options.isReferenceType ? item.phetioID : // TODO: assert that phetioID is defined
```

**Comment by zepumph** [comment] 2019-07-19 00:43
I wanted to add the following code, which works in all cases but in MAL:
```diff
Index: js/ObservableArrayIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/ObservableArrayIO.js	(revision ce896b93b1bb62547d6fa2a1273f593b0ca5ad02)
+++ js/ObservableArrayIO.js	(date 1563496836936)
@@ -97,7 +97,12 @@
           }
           return {
             array: observableArray.getArray().map( function( item ) {
-              return options.isReferenceType ? item.phetioID : // TODO: assert that phetioID is defined
+              if ( options.isReferenceType ) {
+                assert && assert( item.phetioID || item.tandem,
+                  'phetioID should be defined if serializing as a reference type.' );
+                return item.phetioID || item.tandem.phetioID;
+              }
+              return options.isReferenceType ? item.phetioID :
                      elementType.toStateObject( item );
             } )
           };

```

The problem is that we aren't currently instrumenting the broken apart molecules, even though they get added to the oberservable array. It seems like the serialization for that case is broken, but I'll need to investigate this more. Thanks for making the issue.

**Comment by zepumph** [comment] 2020-09-02 22:21
The toStateObject in ObservableArrayIO now looks quite a bit nicer:

```js

    /**
     * @override
     * @param {ObservableArray} observableArray
     * @returns {{array: Array.<*>}}
     * @public
     */
    static toStateObject( observableArray ) {
      validate( observableArray, this.validator );
      return {
        array: observableArray.getArray().map( item => parameterType.toStateObject( item ) )
      };
    }

```

There are no TODOs in that file. Closing

**Closed by zepumph** 2020-09-02 22:21 UTC
Labels: dev:code-review, dev:phet-io
