### ISSUE TITLE
rename DerivedProperty.detach to dispose?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#38] opened 2014-12-09 21:53 UTC
I've been following the scenery/scenery-phet/sun convention of using `dispose` as the name of the function that does cleanup at the end of an object's lifetime.  Should we rename `DerivedProperty.detach` to `dispose`, so that it's consistent with this naming convention? (And rename similarly for other AXON APIs.)

Assigning to @samreid as the author of DerivedProperty.detach, but other developers please chime in.

**Comment by pixelzoom** [comment] 2015-01-27 23:30
@jbphet @samreid @jonathanolson What do you think of changing AXON to use `dispose` rather than `detach`?

**Comment by samreid** [comment] 2015-01-28 04:03
I like that the same name gives a sense of symmetry to the Axon/Sun APIs, but practically it also means that searching for all usages of axon.dispose will be more difficult because sun.dispose will show up in text searches as well.  Not sure what is best here.  I'd like to hear from others.

**Comment by pixelzoom** [comment] 2015-01-29 03:30
Yes, I'd like to hear from others too. @jbphet and @jonathanolson again, your feedback is requested.

**Comment by jonathanolson** [comment] 2015-01-29 03:49
From the words alone, I would have the intuition "I can't use the derived property after dispose()", but "I could use the derived property after detach(), but it just won't update from its dependencies".

If it's truly the "end of lifetime" for the property (i.e. don't call property.value afterwards), then I slightly prefer "dispose". Otherwise "detach" seems to work better.

**Comment by pixelzoom** [comment] 2015-01-29 20:33
We discussed either leaving as is, or changing to dispose and removing all of its listeners. Consensus was to leave as is.

**Comment by samreid** [comment] 2015-01-31 11:24
I should have been a bit more vocal at the meeting--though I do not feel very strongly about it, I do think it would be a good move to switch to dispose() but that this is not a very high priority issue.  Thoughts?

**Comment by jonathanolson** [comment] 2015-01-31 17:14
I don't mind either way.

**Comment by samreid** [comment] 2015-02-01 05:46
@pixelzoom are you ok to leave this as a "to do" item at low priority as described above?

**Comment by pixelzoom** [comment] 2015-02-01 05:57
Yes, ok leaving low priority.

**Comment by samreid** [comment] 2015-04-03 18:10
I'm about to add Property.dispose and PropertySet.dispose.  Note that renaming DerivedProperty.detach=> dispose will have a conflict after I add those.

**Comment by samreid** [comment] 2015-04-03 18:13
I added PropertySet.dispose and Property.dispose above.  

Wondering if this could cause any problems in existing PropertySet subclasses that also declare dispose. (Other than the fact that they would probably want to call super.dispose()).  @pixelzoom do you think this will be a problem?

**Comment by pixelzoom** [comment] 2015-04-03 19:21
In an uninstrumented sim, pairing of link/unlink and new/dispose is required to prevent memory leaks. So when instrumenting code that has properly paired link/unlink and new/dispose, Property.dispose should have to remove 0 observers.  If it removes any observers, then it's masking a memory leak.  So I think that calling dispose should throw an assertion if there are any observers registered for the Property.  Similarly for PropertySet.

**Comment by samreid** [comment] 2015-04-09 18:31
@aaronsamuel137 are you available to familiarize yourself with this thread, see if asserts make sense there, and test a few sims out to see if they are throwing assertion errors for this case?

**Comment by aaronsamuel137** [comment] 2015-04-09 21:49
I can take a look. What's the priority of this? Next week is the earliest I could get to it.

**Comment by samreid** [comment] 2015-04-09 23:08
Anything within 2 weeks would be fine.  If you don't get time before then, just let me know.  Thanks!

**Comment by ariel-phet** [comment] 2015-11-06 19:05
Looks like this is an old issue. @samreid can you take care of, close, or reassign (not to @aaronsamuel137 ) if further action is needed.

**Comment by samreid** [comment] 2015-11-07 02:54
The main problem in this issue has been addressed, the reason the issue is still open is described in https://github.com/phetsims/axon/issues/38#issuecomment-89396284 .  I'll create a separate issue for that and close this one.

**Closed by samreid** 2015-11-07 02:54 UTC
